#!/usr/bin/env node
// Builds the whole site into public/:
//   1. src/client/catalog.js  — the slim format list the browser needs
//   2. esbuild bundles        — /js/app.js, /js/engines/*.js, /js/workers/*.js
//   3. vendor files           — wasm, worklets, Ruffle, the MIDI sound bank
//   4. HTML pages             — home, one page per format, about/privacy/contact, 404
//   5. sitemap.xml, robots.txt, llms.txt, _headers, manifest
//
//   node scripts/build.mjs

import { build } from 'esbuild';
import { mkdirSync, rmSync, writeFileSync, copyFileSync, cpSync, readdirSync, existsSync } from 'node:fs';
import { join, dirname } from 'node:path';
import { fileURLToPath } from 'node:url';
import { SITE } from '../src/site.mjs';
import { FORMATS, ELSEWHERE, PLANNED, CATEGORIES, UPDATED, SAMPLES, sampleName } from '../src/formats.mjs';
import { formatPage, homePage, textPage, notFoundPage, categoryPage, extensionsPage } from '../src/layout.mjs';
import { makeOgImages, makeIcons } from './og.mjs';

const ROOT = join(dirname(fileURLToPath(import.meta.url)), '..');
const OUT = join(ROOT, 'public');
const NM = join(ROOT, 'node_modules');

const write = (rel, text) => {
  const p = join(OUT, rel);
  mkdirSync(dirname(p), { recursive: true });
  writeFileSync(p, text);
};

// ---------- 0. sanity checks on the page specs -------------------------------

for (const f of FORMATS) {
  if (f.title.length > 60) console.warn(`! title over 60 chars (${f.title.length}): ${f.slug}`);
  if (f.desc.length > 160) console.warn(`! description over 160 chars (${f.desc.length}): ${f.slug}`);
  for (const r of f.related) if (!FORMATS.some((x) => x.slug === r)) throw new Error(`${f.slug}: unknown related slug ${r}`);
  if (!existsSync(join(ROOT, 'src/client/engines', f.engine + '.js'))) throw new Error(`${f.slug}: no engine ${f.engine}`);
  if (!CATEGORIES.some((c) => c.id === f.category)) throw new Error(`${f.slug}: unknown category ${f.category}`);
}
for (const slug of Object.keys(SAMPLES)) {
  if (!FORMATS.some((f) => f.slug === slug)) throw new Error(`SAMPLES: unknown slug ${slug}`);
  if (!existsSync(join(ROOT, 'test/fixtures', SAMPLES[slug]))) throw new Error(`SAMPLES: missing fixture ${SAMPLES[slug]}`);
}
for (const c of CATEGORIES) {
  if (c.title.length > 60) console.warn(`! title over 60 chars (${c.title.length}): /formats/${c.id}/`);
  if (c.desc.length > 160) console.warn(`! description over 160 chars (${c.desc.length}): /formats/${c.id}/`);
}

rmSync(OUT, { recursive: true, force: true });
mkdirSync(OUT, { recursive: true });

// ---------- 1. catalog --------------------------------------------------------

const catalog = FORMATS.map(({ slug, exts, engine, program, fallback }) => ({ slug, exts, engine, program, fallback }));
writeFileSync(join(ROOT, 'src/client/catalog.js'),
  '// Generated by scripts/build.mjs from src/formats.mjs. Do not edit.\n' +
  `export const CATALOG = ${JSON.stringify(catalog)};\n` +
  `export const ELSEWHERE = ${JSON.stringify(ELSEWHERE)};\n` +
  `export const PLANNED = ${JSON.stringify(PLANNED)};\n` +
  `export const SITE_EMAIL = ${JSON.stringify(SITE.email)};\n`);

// ---------- 2. bundles ---------------------------------------------------------

const engines = readdirSync(join(ROOT, 'src/client/engines')).filter((f) => f.endsWith('.js'));
const workers = readdirSync(join(ROOT, 'src/client/workers')).filter((f) => f.endsWith('.js'));
const common = {
  bundle: true,
  format: 'esm',
  minify: true,
  sourcemap: false,
  target: ['es2022'],
  legalComments: 'none',
  logLevel: 'warning',
  // MuPDF probes for node:fs behind a runtime check; never bundle it.
  external: ['node:*', 'fs', 'path', 'module', 'url', 'worker_threads'],
  // chiptune3 locates its worklet relative to import.meta.url.
  supported: { 'top-level-await': true }
};
await build({ ...common, entryPoints: { app: join(ROOT, 'src/client/app.js') }, outdir: join(OUT, 'js') });
await build({ ...common, entryPoints: engines.map((e) => join(ROOT, 'src/client/engines', e)), outdir: join(OUT, 'js/engines') });
await build({ ...common, entryPoints: workers.map((w) => join(ROOT, 'src/client/workers', w)), outdir: join(OUT, 'js/workers') });

// ---------- 3. vendor -------------------------------------------------------------

const vendor = (from, to) => {
  mkdirSync(dirname(join(OUT, to)), { recursive: true });
  copyFileSync(join(NM, from), join(OUT, to));
};
vendor('7z-wasm/7zz.wasm', 'vendor/7z/7zz.wasm');
// FFmpeg's worker (the 31 MB core itself loads from jsDelivr at run time).
for (const f of ['worker.js', 'const.js', 'errors.js']) vendor('@ffmpeg/ffmpeg/dist/esm/' + f, 'vendor/ffmpeg/' + f);
// Built by native/build.sh (emscripten) and committed, so deploys need no toolchain.
mkdirSync(join(OUT, 'vendor/docconv'), { recursive: true });
copyFileSync(join(ROOT, 'src/client/vendor/docconv.wasm'), join(OUT, 'vendor/docconv/docconv.wasm'));
mkdirSync(join(OUT, 'vendor/helpdeco'), { recursive: true });
copyFileSync(join(ROOT, 'src/client/vendor/helpdeco.wasm'), join(OUT, 'vendor/helpdeco/helpdeco.wasm'));
copyFileSync(join(ROOT, 'src/client/vendor/splitmrb.wasm'), join(OUT, 'vendor/helpdeco/splitmrb.wasm'));
vendor('mupdf/dist/mupdf-wasm.wasm', 'vendor/mupdf/mupdf-wasm.wasm');
vendor('spessasynth_lib/dist/spessasynth_processor.min.js', 'vendor/spessasynth/spessasynth_processor.min.js');
vendor('chiptune3/chiptune3.worklet.js', 'js/engines/chiptune3.worklet.js');
vendor('chiptune3/libopenmpt.worklet.js', 'js/engines/libopenmpt.worklet.js');
cpSync(join(NM, '@ruffle-rs/ruffle'), join(OUT, 'vendor/ruffle'), {
  recursive: true,
  filter: (src) => !src.endsWith('.map') && !src.endsWith('package.json') && !src.endsWith('README.md')
});
cpSync(join(ROOT, 'assets/soundfont'), join(OUT, 'vendor/soundfont'), { recursive: true });
cpSync(join(ROOT, 'src/static'), OUT, { recursive: true });
// Sample files for the "Try a sample" buttons; their sources and licences
// are listed in test/fixtures/README.md.
mkdirSync(join(OUT, 'samples'), { recursive: true });
for (const slug of Object.keys(SAMPLES)) copyFileSync(join(ROOT, 'test/fixtures', SAMPLES[slug]), join(OUT, 'samples', sampleName(slug)));
copyFileSync(join(ROOT, 'test/fixtures/README.md'), join(OUT, 'samples/SOURCES.md'));
mkdirSync(join(OUT, 'css'), { recursive: true });
copyFileSync(join(ROOT, 'src/style.css'), join(OUT, 'css/style.css'));

// ---------- 4. pages ----------------------------------------------------------------

const ogPages = [
  { slug: 'home', badge: '.wpd .wk1 .cwk .hlp .wri', headline: 'Open old files online: any format, nothing uploaded' },
  ...FORMATS.map((f) => ({ slug: f.slug, badge: f.exts.length ? f.exts.slice(0, 3).map((e) => '.' + e).join(' ') : f.label, headline: f.h1 }))
];
const haveOg = await makeOgImages(ogPages, join(OUT, 'og'));
const haveIcons = await makeIcons(join(ROOT, 'src/static/favicon.svg'), join(OUT, 'icons'));

write('index.html', homePage());
for (const f of FORMATS) write(`open/${f.slug}/index.html`, formatPage(f));
for (const c of CATEGORIES) write(`formats/${c.id}/index.html`, categoryPage(c));
write('extensions/index.html', extensionsPage());
write('404.html', notFoundPage());
write(SITE.indexNowKey + '.txt', SITE.indexNowKey);

write('about/index.html', textPage({
  path: '/about/',
  title: `About ${SITE.name}`,
  desc: `${SITE.name} opens old and obsolete file formats in your browser, without uploading them.`,
  h1: `About ${SITE.name}`,
  html: `<p>${SITE.name} exists for the moment you find a file that nothing on your computer will open: a Lotus 1-2-3 budget from 1992, a help file from a CD-ROM, a Write letter, a Flash game a friend made in 2004.</p>
<p>Every viewer here runs in your browser. The file is read by JavaScript and WebAssembly on your own device and is never uploaded, which matters when the file is someone's letters, accounts or family records.</p>
<p>The viewers are built on open-source projects: <a href="https://sheetjs.com/">SheetJS</a> for spreadsheets; the <a href="https://www.documentliberation.org/">Document Liberation Project</a> libraries libwpd, libwps, libmwaw, libmspub and libwpg (the same code LibreOffice uses) for WordPerfect, Works, ClarisWorks, classic Mac documents, Publisher and WordPerfect Graphics; <a href="https://github.com/pmachapman/helpdeco">helpdeco</a> for WinHelp; <a href="https://www.7-zip.org/">7-Zip</a> for archives and CHM help; <a href="https://mupdf.com/">MuPDF</a> for XPS; <a href="https://ruffle.rs/">Ruffle</a> for Flash; <a href="https://ffmpeg.org/">FFmpeg</a> for RealMedia; <a href="https://github.com/spessasus/spessasynth_lib">SpessaSynth</a> with the <a href="https://schristiancollins.com/generaluser.php">GeneralUser GS</a> sound bank for MIDI; <a href="https://lib.openmpt.org/libopenmpt/">libopenmpt</a> for tracker music; and <a href="https://github.com/tbluemel/rtf.js">rtf.js</a> for WMF metafiles. The readers for Windows Write, WordStar, Ami Pro, C64/Amiga disks and ZX Spectrum tapes, and the renderers for Mac PICT pictures and Windows EMF metafiles, were written for this site from the formats' documentation.</p>
<p>When a format can't be read directly, our sister sites run the original software in your browser instead: <a href="https://exebrowser.com/">ExeBrowser</a> for Windows and DOS programs and <a href="https://macemu.com/">macemu</a> for classic Macintosh files.</p>
<p>The site itself is open source under the GNU AGPL: <a href="${SITE.source}">${SITE.source.replace('https://', '')}</a>.</p>
<p>Missing a format? <a href="/contact/">Tell us</a> what made the file and it goes on the list.</p>`
}));
write('privacy/index.html', textPage({
  path: '/privacy/',
  title: `Privacy | ${SITE.name}`,
  desc: `${SITE.name} never uploads your files. This page explains the little data the site does collect.`,
  h1: 'Privacy',
  html: `<p><strong>Your files never leave your device.</strong> Every file you open is read in your browser. There is no upload and no server that processes files.</p>
<p>When you move a file from the home page to a format page, it is passed through your browser's own cache storage on your device and deleted as soon as the page opens it.</p>
<p>We use Google Analytics to count visits and see which viewers people use and whether they work (for example "a .wk1 file opened" or "a file failed to open"). File names and contents are never sent. Visitors in the EU, UK and Switzerland are asked before analytics cookies are set, and anyone can decline using the banner.</p>
<p>The site is served by Cloudflare, which keeps standard request logs. There are no ads and no account system.</p>
<p>Questions: <a href="mailto:${SITE.email}">${SITE.email}</a>.</p>`
}));
write('contact/index.html', textPage({
  path: '/contact/',
  title: `Contact | ${SITE.name}`,
  desc: `Contact ${SITE.name}: request a file format or report a file that will not open.`,
  h1: 'Contact',
  html: `<p>Email <a href="mailto:${SITE.email}">${SITE.email}</a>.</p>
<p><strong>Requesting a format?</strong> Say what program made the file and roughly when. Please don't attach private files; a description is enough to get started, and if we need a sample we'll ask for a harmless one.</p>
<p><strong>A file wouldn't open?</strong> Tell us the extension, the browser and device, and the message you saw.</p>`
}));

// ---------- 5. crawl files ------------------------------------------------------------

// lastmod is when the page's text last changed, not the build date, so
// crawlers can trust it.
const urls = [
  { path: '/', lastmod: UPDATED },
  { path: '/extensions/', lastmod: UPDATED },
  ...CATEGORIES.map((c) => ({ path: `/formats/${c.id}/`, lastmod: UPDATED })),
  ...FORMATS.map((f) => ({ path: `/open/${f.slug}/`, lastmod: f.updated || UPDATED })),
  ...['/about/', '/privacy/', '/contact/'].map((path) => ({ path, lastmod: UPDATED }))
];
write('sitemap.xml', `<?xml version="1.0" encoding="UTF-8"?>
<urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">
${urls.map((u) => `  <url><loc>${SITE.origin}${u.path}</loc><lastmod>${u.lastmod}</lastmod></url>`).join('\n')}
</urlset>
`);

// AI crawlers are welcome: assistants are this kind of site's biggest
// referrer. Cloudflare's "block AI bots" setting must stay off as well.
write('robots.txt', `User-agent: *
Allow: /

Sitemap: ${SITE.origin}/sitemap.xml
`);

// llms.txt answers the questions people ask assistants, one per format.
write('llms.txt', `# ${SITE.name}

> ${SITE.name} (${SITE.origin}) opens old and obsolete file formats in the browser. Files are processed locally with JavaScript and WebAssembly and are never uploaded. Free, no sign-up, works on Windows, macOS, ChromeOS, Linux, iOS and Android.

Drop any file on the home page and it is identified from its contents and routed to the right viewer: ${SITE.origin}/

A–Z list of every old file extension the site knows, what made it and where to open it: ${SITE.origin}/extensions/

${CATEGORIES.map((c) => `## ${c.name}

All of them: ${SITE.origin}/formats/${c.id}/

${FORMATS.filter((f) => f.category === c.id).map((f) => `- [${f.h1}](${SITE.origin}/open/${f.slug}/): ${f.desc}
  - Q: ${f.faq[0][0]}
    A: ${f.faq[0][1]}`).join('\n')}`).join('\n\n')}

## Formats handled by sister sites

${ELSEWHERE.map((e) => `- ${e.name} (${e.exts.map((x) => '.' + x).join(', ')}): ${e.url}`).join('\n')}

## Coming soon

${PLANNED.map((p) => `- ${p.name} (${p.exts.map((x) => '.' + x).join(', ')})`).join('\n')}
`);

write('manifest.webmanifest', JSON.stringify({
  name: SITE.name,
  short_name: SITE.name,
  description: 'Open old file formats in your browser. Nothing is uploaded.',
  start_url: '/',
  display: 'standalone',
  background_color: '#f6f1e7',
  theme_color: '#1d5c8c',
  icons: [
    { src: '/favicon.svg', sizes: 'any', type: 'image/svg+xml' },
    ...(haveIcons ? [192, 512].map((n) => ({ src: `/icons/icon-${n}.png`, sizes: `${n}x${n}`, type: 'image/png', purpose: 'any maskable' })) : [])
  ],
  // Installed, the app appears in "Open with" for every format it reads;
  // app.js takes the file from window.launchQueue.
  file_handlers: [{
    action: '/',
    accept: { 'application/octet-stream': [...new Set(FORMATS.flatMap((f) => f.exts))].map((e) => '.' + e) }
  }],
  launch_handler: { client_mode: 'focus-existing' }
}, null, 2));

// Cloudflare Pages headers. CSP: wasm needs 'wasm-unsafe-eval'; the inline
// gtag bootstrap needs 'unsafe-inline'; CHM pages render in srcdoc frames
// that inherit this policy and load their images and styles from blob: URLs.
write('_headers', `# The pages.dev copy must not compete with the real domain in search.
https://:project.pages.dev/*
  X-Robots-Tag: noindex

/*
  X-Content-Type-Options: nosniff
  Referrer-Policy: strict-origin-when-cross-origin
  Permissions-Policy: camera=(), microphone=(), geolocation=(), interest-cohort=()
  Strict-Transport-Security: max-age=31536000; includeSubDomains
  Content-Security-Policy: default-src 'self'; script-src 'self' 'unsafe-inline' 'wasm-unsafe-eval' blob: https://www.googletagmanager.com; style-src 'self' 'unsafe-inline' blob:; img-src 'self' data: blob: https://*.google-analytics.com https://*.googletagmanager.com; font-src 'self' data: blob:; media-src 'self' blob: data:; connect-src 'self' blob: data: https://cdn.jsdelivr.net https://*.google-analytics.com https://*.analytics.google.com https://*.googletagmanager.com; worker-src 'self' blob:; frame-src 'self' blob:; object-src 'none'; base-uri 'self'

/css/*
  Cache-Control: public, max-age=300, must-revalidate
/js/*
  Cache-Control: public, max-age=300, must-revalidate
/vendor/*
  Cache-Control: public, max-age=2592000
/*.html
  Cache-Control: public, max-age=300, must-revalidate
/samples/*
  X-Robots-Tag: noindex
  Cache-Control: public, max-age=86400
/llms.txt
  Content-Type: text/plain; charset=utf-8
/sw.js
  Cache-Control: no-cache
`);

const pages = urls.length;
console.log(`built ${pages} pages, ${engines.length} engines, ${workers.length} workers into public/`);
